name: Post PR size summary

# This workflow will run whenever a review is requested on a pull request
# in the repository where this workflow is stored.
on:
  pull_request:
    types:
      - review_requested

# This workflow will use the built in `GITHUB_TOKEN` to
# check out the repository contents,
# get information about the pull request,
# and comment on the pull request.
# This grants `GITHUB_TOKEN` permission to do that.
permissions:
  contents: read
  pull-requests: write

jobs:
  add-to-board:
    name: Add to review board
    # todo change test-team
    if: ${{ github.event.requested_team.name == 'test-team' }}
    runs-on: ubuntu-latest
    steps:
      # This workflow will run a script that is stored in the repository.
      # This step checks out the repository contents so that the workflow can access the script.
      - name: Check out repo content
        uses: actions/checkout@v4

      # This step sets up Node.js
      # The script that this workflow will run uses Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      # This step installs the octokit library.
      # The script that this workflow will run uses the octokit library.
      - name: Install dependencies
        run: npm install octokit

      # This step sets some environment variables,
      # then runs a script to comment on the pull request with an estimate of the size of the pull request.
      - name: Run script
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_NAME: ${{ github.event.pull_request.base.repo.name }}
          REPO_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node .github/workflows/scripts/about-pr-test.js
        # todo change file name
