
# When a pull request that edits the OpenAPI schema is opened, reopened, or synchronized, this workflow will todo
# todo this creates a new docs pr every time, but we only want one docs pr per gh pr that we continually update

name: Build REST API docs preview

on:
  workflow_dispatch: # todo delete this trigger once testing is complete
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'app/api/description/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  build_docs_preview:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
      # todo update the hardcoded pwd everywhere in this file, or store this in a variable

    - name: Check out the github/github repo
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        path: 'github'

    - name: Check out the github/docs-internal repo 
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        repository: "ske-test-org/second-repo" # todo change repo name everywhere in this file
        path: 'second-repo'
        token: ${{ secrets.PAT_preview }} # todo need to add this secret to the gh repo and put in docs eng rotation. it is a fg pat with contents write and pr write permissions and access to both repos.
        branch: ${{ github.ref_name }}_openapi_docs_preview

    - name: Setup Node.js
      uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
      with:
        node-version: '16'

    - run: |-
        cd /home/runner/work/test-org-repo/test-org-repo/second-repo
        cat newFile.txt
        git ls-remote --heads origin

    - name: Checkout or create a docs branch
      run: |-
        cd /home/runner/work/test-org-repo/test-org-repo/second-repo
        git config --global user.name "docs-bot"
        git config --global user.email "77750099+docs-bot@users.noreply.github.com"
        git checkout $BRANCH_NAME 2>/dev/null || git checkout -b $BRANCH_NAME
        git pull
      env:
        BRANCH_NAME: ${{ github.ref_name }}_openapi_docs_preview

    - run: |-
        cd /home/runner/work/test-org-repo/test-org-repo/second-repo
        cat newFile.txt

    - name: Generate the docs data files
      run: |- # todo this only builds rest files; also want to build webhook files
        cd /home/runner/work/test-org-repo/test-org-repo/second-repo
        npm install
        npm run sync-rest

    - run: |- # todo can delete this step
        cd /home/runner/work/test-org-repo/test-org-repo/second-repo
        cat newFile.txt
        git status

    # If there are not changes to commit, this step will fail and the subsequent steps will not run
    - name: Push the docs data files
      run: |-
        cd /home/runner/work/test-org-repo/test-org-repo/second-repo
        git config --global user.name "docs-bot"
        git config --global user.email "77750099+docs-bot@users.noreply.github.com"
        git add .
        git commit -m "generate OpenAPI data files"
        git push --set-upstream origin HEAD

    - name: Open a docs-internal PR
      run: |-
        cd /home/runner/work/test-org-repo/test-org-repo/second-repo
        gh pr create --title "[FOR PREVIEW ONLY] Preview for todo" --body "todo"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_preview }}
