# This workflow is a placeholder so that we can get the workflow on `master` in order to test some things on a branch.

name: Docs preview for OpenAPI changes

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to preview'
        required: false
        default: 'master'

permissions:
  contents: read
  pull-requests: write

jobs:
  build_docs_preview:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder step
      run: |-
        echo "test this on another branch"
