
# When a pull request that edits the OpenAPI schema is opened, reopened, or synchronized, this workflow todo

name: Build REST API docs preview

on:
  workflow_dispatch: # todo delete this trigger
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'app/api/description/**'

permissions:
  pull-requests: write

  # check out repo contents
  # shallow clone docs internal
  # cd to docs internal
  # make docs internal branch
  # generate the rest data files
  # push to docs internal
jobs:
  build_docs_preview:
    runs-on: ubuntu-latest
    steps:
    - run: ls
    - name: Check out github/github repo
      uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      with:
        path: 'repo-gh'

    - run: ls
    - run: |-
        mkdir repo-di
        cd repo-di
        git clone https://github.com/ske-test-org/second-repo.git --depth 1 --branch main
        ls
    - run: ls
    - run: cd ..
    - run: ls
