name: Call a reusable workflow

on:
 workflow_dispatch:

jobs:
  ReuseableMatrixJobForDeployment:
#     strategy:
#       matrix:
#         env: [dev, stage, prod]
    uses: ske-test-org/test-org-repo/.github/workflows/called.yml@main
#     with:
#       env: ${{ matrix.env }}
