name: How to get reviewed
on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  comment_about_review:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Comment on the PR
        run: |
          gh pr comment $PR --body ":wave: Thank you for opening this PR! When you are ready for review by the docs team, add the \`ready-for-doc-review\` label. This will add your PR to our [review board](https://github.com/orgs/github/projects/2936)."
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PR: ${{ github.event.pull_request.html_url }}
