name: Context

on:
  workflow_dispatch:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: event
        run: |
          echo $GITHUB_EVENT_NAME
      - name: context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo $GITHUB_CONTEXT
      - name: if issue
        if: ${{ github.event_name == 'issues' }}
        run: |
          echo "it's an issue"
      - name: if pr
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "it's a pr"
