name: Add docs-reviewers request to FR board

# **What it does**: 
# **Why we have it**: 
# **Who does it impact**: 

on:
  workflow_dispatch
  # todo also add schedule

jobs:
  add-requests-to-board:
    name: Add requests to board
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo content
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run script
        run: |
          fr-add-docs-reviewers-requests.js
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
          VAR: "hello"
