name: Add docs-reviewers request to FR board

# **What it does**: 
# **Why we have it**: 
# **Who does it impact**: 

on:
  - workflow_dispatch
  - push
  # todo also add schedule

jobs:
  add-requests-to-board:
    name: Add requests to board
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo content
        uses: actions/checkout@v2

      - name: Check node version
        run: node -v

      - name: Install dependencies
        run: npm install @octokit/graphql

      - name: Run script
        run: |
          node fr-add-docs-reviewers-requests.js
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
          VAR: "hello"
