name: Dollar

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Server to deploy to (staging|test|prod)'
        required: true
        default: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_VALUE: initial
      VAL_FROM_SECRET: initial

    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=$yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}"

      - name: Set the value
        id: step_one1
        run: |
          echo "action_state=/$yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two1
        run: |
          echo "${{ env.action_state }}"

      - name: Set the value
        id: step_one2
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two2
        run: |
          echo "${{ env.action_state }}"

      - shell: pwsh
        run: |
          echo "SAR=$test" >> $GITHUB_ENV

      - shell: pwsh
        run: |
          echo $SAR

      - shell: pwsh
        run: |
          echo "TEMPLATE<<EOF" >> $GITHUB_ENV
          echo "$test" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - shell: pwsh
        run: |
          echo $TEMPLATE

      - shell: pwsh
        run: |
          echo "TEST_VALUE=$test"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo "VAL_FROM_SECRET=${{ secrets.SECRET_VALUE }}"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo "Running on test (${{ github.event.inputs.server }}) environment"

      - shell: pwsh 
        run: |
          echo "TEST_VALUE='${{ env.TEST_VALUE }}' and VAL_FROM_SECRET='${{ env.VAL_FROM_SECRET }}'"

      - shell: pwsh
        run: |
          echo 'TEST_VALUE=$test' | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo 'VAL_FROM_SECRET=${{ secrets.SECRET_VALUE }}' | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - shell: pwsh 
        run: |
          echo "TEST_VALUE='${{ env.TEST_VALUE }}' and VAL_FROM_SECRET='${{ env.VAL_FROM_SECRET }}'"

      - shell: pwsh
        run: |
          echo "TEST_VALUE='$test'"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
          echo "VAL_FROM_SECRET='${{ secrets.SECRET_VALUE }}'" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - shell: pwsh 
        run: |
          echo "TEST_VALUE='${{ env.TEST_VALUE }}' and VAL_FROM_SECRET='${{ env.VAL_FROM_SECRET }}'"
