name: Dollar

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Server to deploy to (staging|test|prod)'
        required: true
        default: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEST_VALUE: initial
      VAL_FROM_SECRET: initial

    steps:
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=$yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}"

      - name: Set the value
        id: step_one1
        run: |
          echo "action_state=%$yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two1
        run: |
          echo "${{ env.action_state }}"

      - name: Set the value
        id: step_one2
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two2
        run: |
          echo "${{ env.action_state }}"
