name: Dollar



on:
  pull_request:
    types: [review_requested]
jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    if: >
      ${{ contains(github.event.pull_request.requested_reviewers.*.login, 'ske-test-org/test-team') }}
    steps:
      - run: echo 'A review from octo-team was requested'
