name: contains

on:
  issues:
    types:
      - labeled
      
jobs:
  contains:
    if: (!contains(github.event.issue.labels.*.name, 'aaa'))
    runs-on: ubuntu-latest

    steps:
    - name: one
      run: |
        echo ${{ contains(github.event.pull_request.labels.*.name, 'aaa') }}
        echo ${{contains(join(github.event.pull_request.labels.*.name, ', '),'aaa')}}
        echo ${{contains(github.event.pull_request.labels.*.name,'needs')}}
        echo $VAR1
        echo $VAR2
        echo $VAR3
      env:
       VAR1: ${{ contains(github.event.pull_request.labels.*.name, 'aaa') }}
       VAR2: ${{contains(join(github.event.pull_request.labels.*.name, ', '),'aaa')}}
       VAR3: ${{contains(github.event.pull_request.labels.*.name,'needs')}}


  contains2:
    if: (contains(github.event.issue.labels.*.name, 'aaa'))
    runs-on: ubuntu-latest

    steps:
    - name: two
      run: |
        echo ${{ contains(github.event.pull_request.labels.*.name, 'aaa') }}
        echo ${{ contains(join(github.event.pull_request.labels.*.name, ', '),'aaa') }}
        echo ${{ contains(github.event.pull_request.labels.*.name,'needs') }}
        echo $VAR1
        echo $VAR2
        echo $VAR3
        echo ${{ contains('Hello world', 'llo') }}
        echo ${{ github.event.pull_request.labels }}
        echo ${{ github.event.pull_request.labels.*.name }}

      env:
       VAR1: ${{ contains(github.event.pull_request.labels.*.name, 'aaa') }}
       VAR2: ${{ contains(join(github.event.pull_request.labels.*.name, ', '),'aaa') }}
       VAR3: ${{ contains(github.event.pull_request.labels.*.name,'needs') }}

  contains3:
    if: contains(join(github.event.pull_request.labels.*.name, ', '),'aaa')
    runs-on: ubuntu-latest

    steps:
    - name: three
      run: |
        echo ${{ contains(github.event.pull_request.labels.*.name, 'aaa') }}
        echo ${{contains(join(github.event.pull_request.labels.*.name, ', '),'aaa')}}
        echo ${{contains(github.event.pull_request.labels.*.name,'needs')}}
        echo $VAR1
        echo $VAR2
        echo $VAR3
      env:
       VAR1: ${{ contains(github.event.pull_request.labels.*.name, 'aaa') }}
       VAR2: ${{contains(join(github.event.pull_request.labels.*.name, ', '),'aaa')}}
       VAR3: ${{contains(github.event.pull_request.labels.*.name,'needs')}}


