name: contains

on:
  workflow_dispatch:

env:
  PROJECT_ID: a
  IMAGE: static-site

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - run: echo $IMAGE
    - run: echo ${{ env.IMAGE}}
    - run: echo $PROJECT_ID
    - run: echo ${{ env.PROJECT_ID}}
