name: Matrix

# on: [workflow_dispatch, push]
on:
  repository_dispatch:
    types:
      - test
 
jobs:
  print_dispatch:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.versions }}

  test_dispatch:
    runs-on: ubuntu-latest
    env:
      VERSIONS: ${{ github.event.client_payload.versions }}
    strategy:
      matrix:
        version: $VERSIONS
    steps:
      - run: echo ${{ matrix.version }}



#   kpm:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         fruit: [apple, pear]
#         animal: [cat, dog]
#         exclude:
#           - fruit: pear
#           - fruit: apple
#             animal: dog
#     steps:
#       - run: echo ${{ matrix.color }}
#       - run: echo ${{ matrix.fruit }}
#       - run: echo ${{ matrix.animal }}
#       - run: echo ${{ matrix.shape }}

