name: Matrix

on: push
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        version: [12, 14, 16]
        include:
          - os: windows-latest
            version: 17
    steps:
      - run: echo ${{ matrix.version }}

#   kpm:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         fruit: [apple, pear]
#         animal: [cat, dog]
#         exclude:
#           - fruit: pear
#           - fruit: apple
#             animal: dog
#     steps:
#       - run: echo ${{ matrix.color }}
#       - run: echo ${{ matrix.fruit }}
#       - run: echo ${{ matrix.animal }}
#       - run: echo ${{ matrix.shape }}

