name: Matrix

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
#     continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        experimental: [true, false]
        delay: [0, 20]
    steps:
      - run: echo ${{ matrix.experimental }}
      - run: sleep ${{ matrix.delay }}
      - if: ${{ matrix.experimental }}
        run: exit 1


#   kpm:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         fruit: [apple, pear]
#         animal: [cat, dog]
#         include:
#           - color: green
#           - color: pink
#           - fruit: apple
#             shape: circle
#           - fruit: banana
#           - fruit: peach
#             animal: snake
#             color: red
#             shape: square
#           - fruit: plum
#             animal: cat

#     steps:
#       - run: echo ${{ matrix.color }}
#       - run: echo ${{ matrix.fruit }}
#       - run: echo ${{ matrix.animal }}
#       - run: echo ${{ matrix.shape }}


#   includes_only:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         include:
#           - color: red
#             shape: square
#             fruit: apple
#           - color: blue
#             shape: circle
#           - animal: cow
#     steps:
#       - run: echo ${{ matrix.color }}
#       - run: echo ${{ matrix.shape }}
#       - run: echo ${{ matrix.fruit }}
#       - run: echo ${{ matrix.animal }}
        
#   knm:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         fruit: [apple, orange]
#         animal: [dog]
#         include:
#           - color: red
#             shape: square
#     steps:
#       - run: echo ${{ matrix.color }}
#       - run: echo ${{ matrix.shape }}
#       - run: echo ${{ matrix.fruit }}
#       - run: echo ${{ matrix.animal }}

#   kfp_vpm:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         fruit: [apple, orange]
#         animal: [dog]
#         include:
#           - fruit: apple
#             animal: cow
#           - fruit: apple
#             animal: horse
#     steps:
#       - run: echo ${{ matrix.fruit }}
#       - run: echo ${{ matrix.animal }}

#   kpm:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         fruit: [apple, orange]
#         animal: [dog]
#         include:
#           - fruit: apple
#             color: red
#           - fruit: banana
#             color: green
#           - fruit: peach
#             color: yellow
#           - fruit: orange
#             color: purple
#             animal: dog

#     steps:
#       - run: echo ${{ matrix.color }}
#       - run: echo ${{ matrix.fruit }}
#       - run: echo ${{ matrix.animal }}
