name: Matrix

on: [workflow_dispatch, push]

jobs:

#   includes_only:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         include:
#           - color: red
#             shape: square
#             fruit: apple
#           - color: blue
#             shape: circle
#           - animal: cow
#     steps:
#       - env:
#           FRUIT: ${{ matrix.fruit }}
#           ANIMAL: ${{ matrix.animal }}
#         run: echo $FRUIT $ANIMAL
        
#   key_no_match:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         fruit: [apple, orange]
#         animal: [dog]
#         include:
#           - color: red
#             shape: square
#     steps:
#       - env:
#           FRUIT: ${{ matrix.fruit }}
#           ANIMAL: ${{ matrix.animal }}
#         run: echo $FRUIT $ANIMAL

#   key_full_match_value_partial_match:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         fruit: [apple, orange]
#         animal: [dog]
#         include:
#           - fruit: apple
#             animal: cow
#           - fruit: apple
#             animal: horse
#     steps:
#       - env:
#           FRUIT: ${{ matrix.fruit }}
#           ANIMAL: ${{ matrix.animal }}
#         run: echo $FRUIT $ANIMAL

#   key_partial_match:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         fruit: [apple, orange]
#         animal: [dog]
#         include:
#           - fruit: apple
#             color: red
#           - fruit: banana
#             color: green
#           - fruit: peach
#             color: yellow
#           - fruit: orange
#             color: purple
#             animal: dog

#     steps:
#       - env:
#           FRUIT: ${{ matrix.fruit }}
#           ANIMAL: ${{ matrix.animal }}
#         run: echo $FRUIT $ANIMAL

#   example_matrix:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         os: [macos-latest, windows-latest, ubuntu-latest]
#         node: [12, 14, 16]
#         include:
#           - os: windows-latest
#             node: 17
#     steps:
#       - run: echo 1

  ex2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [m,w]
        node: [14, 16]
        include:
          - os: w
            node: 16
            npm: 6
    steps:
      - run: echo ${{ matrix }}
