name: Matrix

on: workflow_dispatch

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fruit: ["apple", "orange", "banana"]
    steps:
      - env:
          FRUIT: ${{ matrix.fruit }}
        run: echo $FRUIT
