name: Automatically open a docs-content tracking issue
on:
  issues:
    types:
      - opened
      - reopened

permissions:
  issues: write
  contents: read

jobs:
  parse_release_issue:
    runs-on: ubuntu-latest

    outputs:
      newTitle: ${{ steps.parse_issue.outputs.newTitle }}
      newBody: ${{ steps.parse_issue.outputs.newBody }}
      ghesLabels: ${{ steps.parse_issue.outputs.ghesLabels }}
      tier: ${{ steps.parse_issue.outputs.tier }}

    steps:
      - name: Check out repo content
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @actions/github @actions/core

      - name: Parse release issue
        id: parse_issue
        run: node automation/docsParseReleaseIssue.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  open_docs_issue:
    runs-on: ubuntu-latest
    needs: parse_release_issue

    outputs:
      output: ${{ steps.create_docs_issue.outputs.result }}

    steps:
      - name: Check out repo content
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install @actions/github @actions/core

      - name: Create and label an issue in the docs-content repo
        id: create_docs_issue
        run: node automation/docsOpenDocsIssue.js
        env:
          NEW_TITLE: ${{ needs.parse_release_issue.outputs.newTitle }}
          NEW_BODY: ${{ needs.parse_release_issue.outputs.newBody }}
          GHES_LABELS: ${{ needs.parse_release_issue.outputs.ghesLabels }}
          TIER: ${{ needs.parse_release_issue.outputs.tier }}
          DOCS_TOKEN: ${{ secrets.DOCS_BOT_PAT_READPUBLICKEY }}
