name: Is member

on:
  workflow_dispatch
  
jobs:
  is_member:
    runs-on: ubuntu-latest
    steps:
      - name: Check if triggered by a docs team member
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          members="$( gh api graphql -f query='
            query {
              organization(login: "github") {
                team(slug: "docs") {
                  members {
                    nodes {
                      login
                    }
                  }
                }
              }
            }
          ' --jq '.data.organization.team.members.nodes | [(.[].login)]')"
          
          echo $members
          
          echo $GITHUB_ACTOR

          isMember=$(echo ${members[@]} | grep -ow $GITHUB_ACTOR | wc -w)

          if [ $isMember -eq  0 ]
          then
            echo "$GITHUB_ACTOR is not a docs team member. exiting..."
            gh issue edit 76 --remove-label "bug"
            exit 1
          fi
