# Creates a new docs friction sync issue when requested or when an issue with the docs friction sync label is closed

name: Docs friction sync
on:
  workflow_dispatch:
  issues:
    types: [closed]

jobs:
  
  create_issue:
    if: ${{ contains(github.event.issue.labels.*.name, 'docs-office-hours') || (github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - name: Create issue
        run: |
          gh issue create --title "Docs office hours" --body "Previous meeting notes: https://github.com/github/docs-team/labels/docs-office-hours

          Zoom recoding of this meeting: 

          ## Agenda
            - [ ] Remind people to attend on Slack: #docs-content, #docs, #docs-engineering
            - [ ] Designate note taker
            - [ ] Start Zoom recording
            - [ ] Add discussion items here :point_down:
              - [ ] ...

          ## Post-Meeting
            - [ ] Create follow up issues if needed with the `friction` label in the docs-engineering repo
            - [ ] Create follow up discussions if needed to get consensus from docs-content. Advertise on the [docs-content](https://github.com/github/docs-team/labels/hangout-product-docs) sync agenda and in #docs-content.
            - [ ] Post notes in this issue
            - [ ] Add the Zoom recording to this issue
            - [ ] Share the notes and recording on Slack

          /cc @skedwards88

          " --repo $GITHUB_REPOSITORY --label "docs-office-hours"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
