name: Public interfaces office hours agenda
on:
  workflow_dispatch:
  schedule:
  - cron: 10 2 * * 4

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Get date
        run: echo "DATE=$(date -d next-monday '+%b %d, %Y')" >> $GITHUB_ENV
      - name: Create issue
        run: |
          gh issue create --title "Public Interfaces Office Hours for week of ${{ env.DATE }}" --body "<!--
A guide on our Office Hours can be found here: https://github.com/github/ecosystem-api/blob/master/docs/api-office-hours.md
-->

Link to previous meetings: https://github.com/github/public-interfaces/labels/office-hours
  
Link to Zoom: <Link here>

Meeting time: <Time here>

## Agenda

  - [ ] Remind people to attend on Slack: #engineering, #ecosystem-api, #ce-apps, #ecosystem-events, #pi
  - [ ] Who is taking notes?
  - [ ] Record the meeting on Zoom
  - [ ] Add agenda items here 👈 

## Attendees

  - your handle here

## Notes

...

## Action Items

  - [ ] Share recording
  
          " --repo $GITHUB_REPOSITORY --label "office-hours"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
