# Creates a new docs friction sync issue when requested or when an issue with the docs friction sync label is closed

name: Docs friction sync
on:
  workflow_dispatch:
  issues:
    types: [closed]

jobs:
  create_issue:
#     if: ${{ contains(github.event.issue.labels.*.name, 'docs-office-hours') || github.event_name == "workflow_dispatch" }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue
        run: |
          gh issue create --title "Docs office hours" --body "Yo there
          
          hi! some stuff:
          
          - [ ] a
          - [ ] b
          " --repo $GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
