name: Open docs issue

on:
  issues:
    types: [opened, reopened]

jobs:
  open_docs_issue:
    runs-on: ubuntu-latest
    steps:
      - name: View context
        uses: actions/github-script@2b34a689ec86a68d8ab9478298f91d5401337b7d
        with:
          script: console.log(context)

      - name: Parse body
        uses: actions/github-script@2b34a689ec86a68d8ab9478298f91d5401337b7d
        id: parse-body
        with:
          result-encoding: string
          script: |
            const body = context.payload.issue.body

            function getStringBetween(input, before, after) {
              // i = case insensitive, s = match newlines
              re = new RegExp(before + "(.*?)" + after, 'is')
              const result = input.match(re);

              if (result) {
                return result[1].trim();
              } else {
                console.log(`String between ${before} and ${after} was not found. Check if the release template changed.`)
                return result
              }
            }
            
            shipDate = getStringBetween(body, "Expected ship date", "###")
            description = getStringBetween(body, "Short description of the project:", "###")
            newDescription = `The new issue with ${shipDate} and ${description}`
            
            console.log(body)
            console.log(shipDate)
            console.log(description)
            console.log(newDescription)
            return newDescription

      - name: Print new body
        run: echo $DESC
        env:
          DESC: ${{ steps.parse-body.outputs.result }}
          
      - name: Open issue
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        run: gh issue create --title "NEW" --body "content" --repo ske-test-org/second-repo


