name: Ready for docs-content review

# **What it does**: Adds pull requests in the docs-internal repository to the docs-content review board
# **Why we have it**: So that other GitHub teams can easily request reviews from the docs-content team, and so that writers can see when a PR is ready for review
# **Who does it impact**: Writers working in the docs-internal repository

on:
  pull_request:
    types: [labeled]

jobs:
  request_doc_review:
    name: Request a review from the docs-content team
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo content
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Setup Node
        uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm install @octokit/graphql

      - name: Run script
        run: |
          node .github/actions-scripts/ready-for-docs-review.js
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          PROJECT_NUMBER: 10
          ORGANIZATION: 'ske-test-org'
          PR_NODE_ID: ${{ github.event.pull_request.node_id }}
          AUTHOR_LOGIN: ${{ github.event.pull_request.user.login }}
          PR_REPO: ${{ github.event.pull_request.base.repo.full_name }}

# todo if failure, do old action? 
