name: Automatically open a docs-content tracking issue
on:
  issues:
    types:
      - opened
      - reopened # todo remove
jobs:
  auto_open_docs_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Parse release issue
        uses: actions/github-script@2b34a689ec86a68d8ab9478298f91d5401337b7d
        id: parse_issue
        with:
          script: |
            return {
                newTitle: "TITLE",
                docsNeeded: false,
                newBody: "BODY",
                ghaeApplicable: true, 
              };

      - name: Create an issue in the docs-content repo
        run: |
          new_issue_url="$(gh issue create --title "$ISSUE_TITLE" --body "$ISSUE_BODY" --repo ske-test-org/test-org-repo)"
          echo 'NEW_ISSUE='$new_issue_url >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          ISSUE_BODY: ${{ fromJSON(steps.parse_issue.outputs.result).newBody }}
          ISSUE_TITLE: ${{ fromJSON(steps.parse_issue.outputs.result).newTitle }}

      - name: Label release issue GHAE
        if: fromJSON(steps.parse_issue.outputs.result).ghaeApplicable
        env:
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          NEW_ISSUE: ${{ env.NEW_ISSUE }}
        run: |
          gh issue edit $NEW_ISSUE --add-label "Docs-NA"

          
  # TODO:
  # - change repo where issue is created
  # - change PAT secret name
  # - store secret
  # - don't do anything if docs not needed
