name: rest test
on:
  workflow_dispatch:
jobs:
  use_api_via_script:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Check out repo content
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
          cache: npm

      - name: Install dependencies
        run: npm install octokit

      - name: Run script
        env:
          TOKEN: ${{ secrets.GITHUB_TOkEN }}
        run: |
          node .github/actions-scripts/use-the-api.js# jobs:
#   use_api:
#     runs-on: ubuntu-latest
#     permissions: {}
#     steps:
#       - env:
#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           curl --request GET \
#           --url "https://api.github.com/octocat" \
#           --header "Authorization: Bearer $GH_TOKEN"
# jobs:
#   use_api:
#     runs-on: ubuntu-latest
#     permissions: {}
#     steps:
#       - env:
#           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           gh api /octocat
# jobs:
#   use_api_via_script:
#     runs-on: ubuntu-latest
#     permissions: {}
#     steps:
#       - uses: actions/github-script@v6
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           script: |
#             await github.request('GET /octocat', {})
