on: push
jobs:
  my-jobname:
    runs-on: ubuntu-latest
    env:
       MY_SECRET: ${{ secrets.REPO_LEVEL_ORG_WRITE }}
    steps:
      - if: ${{ env.MY_SECRET }}
        run: echo "I have the secret!"

