on: push
jobs:
  secret_access:
    runs-on: ubuntu-latest
    env:
       YES_TOKEN: ${{ secrets.REPO_LEVEL_ORG_WRITE }}
       NO_TOKEN: ${{ secrets.ORG_LEVEL_ORG_WRITE }}
       FAKE_TOKEN: ${{ secrets.ORG_LEVEL_ORG_WRITE }}
    steps:
      - name: yes_token
        if: ${{ env.YES_TOKEN }}
        run: echo ${{ env.YES_TOKEN }}
      - name: no_token
        if: ${{ env.NO_TOKEN }}
        run: echo ${{ env.NO_TOKEN }}
      - name: fake_token
        if: ${{ env.FAKE_TOKEN }}
        run: echo ${{ env.FAKE_TOKEN }}

