name: Req rev

on:
  pull_request_target:
    types: [labeled, review_requested]

permissions:
  contents: read

jobs:
  request_doc_review:
    name: Request a review
    if: >-
      github.repository == 'ske-test-org/test-org-repo' &&
      (github.event.label.name == 'ready-for-doc-review' || github.event.requested_team.name == 'test-team')
    runs-on: ubuntu-latest
    steps:
      - run: echo HI
