on: 
  push:
  workflow_dispatch:

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Get member
        uses: actions/github-script@2b34a689ec86a68d8ab9478298f91d5401337b7d
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            try {
              await github.teams.getMembershipForUserInOrg({
                org: 'github',
                team_slug: 'docs',
                username: context.payload.sender.login,
              });
              console.log('case 1')
              return
            } catch(err) {
              console.log('case 2')

            }
