name: API/events/apps triager
on:
  workflow_dispatch:
  push:
#   to do remove push, add cron
jobs:
  triager:
    runs-on: ubuntu-latest
    steps:
          
#           todo change org login and project number
      - name: Count how many of the most recent 100 items have a status of "triage"
        run: |
          NUMBER_TO_TRIAGE=$(gh api graphql -f query='
            query{
            organization(login: "ske-test-org") {
              projectV2(number: 13) {
                items(last:100) {
                  nodes {
                    fieldValues(first: 100) {
                      nodes {
                        ... on ProjectV2ItemFieldSingleSelectValue {
                          name
                          field {
                            ... on ProjectV2FieldCommon {
                              name
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }' | jq '[.data.organization.projectV2.items.nodes[] | select(.fieldValues.nodes[] | select(.name == "Triage" and .field.name == "Status"))] | length')
          
          echo 'NUMBER_TO_TRIAGE='$NUMBER_TO_TRIAGE >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{secrets.TEMP_PROJECTS}}
    
      - name: Echo count
        run: echo $NUMBER_TO_TRIAGE

      - name: If more than zero # TODO post in slack
        if: ${{ env.NUMBER_TO_TRIAGE > 0 }}
        run: echo "greater than zero"

      - name: If zero
        if: ${{ env.NUMBER_TO_TRIAGE == 0 }}
        run: echo "No items to triage"
